name: ApiUsageTrackerForMac
options:
  bundleIdPrefix: com.mactools
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: NO

targets:
  ApiUsageTrackerForMac:
    type: application
    platform: macOS
    sources:
      - path: Sources/App
        excludes:
          - "**/.DS_Store"
      - path: Sources/Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mactools.apiusagetracker
        PRODUCT_NAME: API Tracker
        INFOPLIST_FILE: Sources/App/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/App/Resources/ApiUsageTrackerForMac.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LSUIElement: YES
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGNING_ALLOWED: NO
    # Desktop widget target is kept in source, but temporarily not embedded in the app
    # due App Group sandbox limitations during current distribution/debug workflow.

  UsageWidget:
    type: app-extension
    platform: macOS
    sources:
      - path: Sources/Widget
        excludes:
          - "**/.DS_Store"
      - path: Sources/Shared
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mactools.apiusagetracker.widget
        PRODUCT_NAME: API Tracker Widget
        INFOPLIST_FILE: Sources/Widget/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/Widget/UsageWidget.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @executable_path/../../../../Frameworks"
        SKIP_INSTALL: YES
      configs:
        Debug:
          CODE_SIGN_STYLE: Automatic
        Release:
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGNING_ALLOWED: NO

schemes:
  ApiUsageTrackerForMac:
    build:
      targets:
        ApiUsageTrackerForMac: all
    run:
      config: Debug
    archive:
      config: Release
